# Generated by Django 5.2 on 2025-10-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF no formato 000.000.000-00', max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
