# Generated by Django 4.2.2 on 2025-10-28 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='foto',
        ),
    ]
